CREATE TABLE Account (
    Id INT IDENTITY(1,1),
    TypeId TINYINT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    StartDateUtc DATETIME2 NOT NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Account_IsActive DEFAULT 1,
    StartBalance DECIMAL(19,4) NOT NULL CONSTRAINT DF_Account_StartBalance DEFAULT 0,
    LastModifiedUtc DATETIME2 NOT NULL CONSTRAINT DF_Account_LastModifiedUtc DEFAULT SYSUTCDATETIME(),

    CONSTRAINT PK_Account PRIMARY KEY (Id),
    CONSTRAINT CK_Account_TypeId CHECK (TypeId BETWEEN 1 AND 5)
);
